/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kırtasiyeotomasyonuu;

import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class anaSayfa extends javax.swing.JFrame {

    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    PreparedStatement statement = null;
    ResultSet resultSet = null;

    private String barkodNo;
    private String ürün_adi;
    private String fiyat;
    private String adet;

    public String getBarkodNo() {
        return barkodNo;
    }

    public void setBarkodNo(String barkodNo) {
        this.barkodNo = barkodNo;
    }

    public String getÜrün_adi() {
        return ürün_adi;
    }

    public void setÜrün_adi(String ürün_adi) {
        this.ürün_adi = ürün_adi;
    }

    public String getFiyat() {
        return fiyat;
    }

    public void setFiyat(String fiyat) {
        this.fiyat = fiyat;
    }

    public String getAdet() {
        return adet;
    }

    public void setAdet(String adet) {
        this.adet = adet;
    }

    public anaSayfa() {
        initComponents();
        //İki seçenek aynı anda seçilmesin diye checkBoxları buttonGroupa ekledim.
        buttonGroup1.add(evetCheckBox);
        buttonGroup1.add(hayırCheckBox);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        satisTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        barkodNo_alani = new javax.swing.JTextField();
        ürünadi_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        adet_alani = new javax.swing.JTextField();
        ekleButonu = new javax.swing.JButton();
        secileniSilButonu = new javax.swing.JButton();
        urunlisteleButonu = new javax.swing.JButton();
        satisGecmisi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        personelAdiAlani = new javax.swing.JTextField();
        musteriAdiAlani = new javax.swing.JTextField();
        personellistele = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        evetCheckBox = new javax.swing.JCheckBox();
        hayırCheckBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        toplam_alani = new javax.swing.JTextField();
        kalan_alani = new javax.swing.JTextField();
        odenenTutarAlani = new javax.swing.JTextField();
        yazdırButonu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fisYazdir = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        müsteridi = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        tamamlandıButonu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem7.setText("jMenuItem7");

        jPasswordField1.setText("jPasswordField1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        satisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod No", "Ürün Adı", "Fiyat", "Adet", "Toplam"
            }
        ));
        satisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                satisTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(satisTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barkod No :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ürün Adı :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fiyat :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Adet :");

        barkodNo_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barkodNo_alaniActionPerformed(evt);
            }
        });
        barkodNo_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barkodNo_alaniKeyPressed(evt);
            }
        });

        ürünadi_alani.setEditable(false);
        ürünadi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürünadi_alaniActionPerformed(evt);
            }
        });

        fiyat_alani.setEditable(false);

        adet_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adet_alaniActionPerformed(evt);
            }
        });

        ekleButonu.setText("Ekle");
        ekleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonuActionPerformed(evt);
            }
        });

        secileniSilButonu.setText("Seçileni Sil ");
        secileniSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secileniSilButonuActionPerformed(evt);
            }
        });

        urunlisteleButonu.setText("Ürün Listele ");
        urunlisteleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunlisteleButonuActionPerformed(evt);
            }
        });

        satisGecmisi.setText("Satış Geçmişi");
        satisGecmisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisGecmisiActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(barkodNo_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ürünadi_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(fiyat_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(adet_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ekleButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(secileniSilButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(urunlisteleButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(satisGecmisi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barkodNo_alani)
                            .addComponent(ürünadi_alani)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiyat_alani)
                            .addComponent(adet_alani)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(satisGecmisi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(urunlisteleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(secileniSilButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ekleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(barkodNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ürünadi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satisGecmisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekleButonu)
                        .addComponent(secileniSilButonu)
                        .addComponent(urunlisteleButonu)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Personelin Adı ve Soyadı : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Müşteri Adı ve Soyadı :");

        musteriAdiAlani.setEditable(false);

        personellistele.setText("Personel Listele");
        personellistele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personellisteleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Müşterinin önceden kaydı var mı ?  ");

        evetCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        evetCheckBox.setText("Evet");
        evetCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evetCheckBoxActionPerformed(evt);
            }
        });

        hayırCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        hayırCheckBox.setText("Hayır ");
        hayırCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hayırCheckBoxActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Toplam : ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kalan :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ödenen Tutar : ");

        toplam_alani.setEditable(false);

        kalan_alani.setEditable(false);
        kalan_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalan_alaniActionPerformed(evt);
            }
        });

        yazdırButonu.setText("Fişi Yazdır ");
        yazdırButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazdırButonuActionPerformed(evt);
            }
        });

        fisYazdir.setColumns(20);
        fisYazdir.setRows(5);
        jScrollPane2.setViewportView(fisYazdir);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ÖDEME ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BİLGİLER");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Müşteri ID :");

        müsteridi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                müsteridiActionPerformed(evt);
            }
        });
        müsteridi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                müsteridiKeyPressed(evt);
            }
        });

        tamamlandıButonu.setText("Ödeme Tamamlandı");
        tamamlandıButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamamlandıButonuActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(personelAdiAlani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(musteriAdiAlani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(personellistele, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(evetCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(hayırCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(toplam_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(kalan_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(odenenTutarAlani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(yazdırButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(müsteridi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(tamamlandıButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(evetCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hayırCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(personelAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personellistele))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(musteriAdiAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                    .addComponent(müsteridi)))))
                    .addComponent(jSeparator8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tamamlandıButonu))
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane3Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(toplam_alani)
                                            .addComponent(odenenTutarAlani, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kalan_alani, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(yazdırButonu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(personelAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personellistele))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hayırCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(evetCheckBox)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(müsteridi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(musteriAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(toplam_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(odenenTutarAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(kalan_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(yazdırButonu))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamamlandıButonu)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(582, 582, 582))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SATIŞ YAPMA EKRANI");

        jDesktopPane4.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jMenu4.setText("Ekle ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu4KeyPressed(evt);
            }
        });
        jMenu4.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Müşteri ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem1KeyPressed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator2);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setText("Ürün");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuItem10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem10KeyPressed(evt);
            }
        });
        jMenu4.add(jMenuItem10);
        jMenu4.add(jSeparator3);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setText("Kategori Ve Marka ");
        jMenuItem9.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuItem9MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem9MouseClicked(evt);
            }
        });
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuItem9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem9KeyPressed(evt);
            }
        });
        jMenu4.add(jMenuItem9);
        jMenu4.add(jSeparator11);
        jMenu4.add(jSeparator4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Listele ");
        jMenu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu3KeyPressed(evt);
            }
        });
        jMenu3.add(jSeparator7);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem4.setText("Ürün ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);
        jMenu3.add(jSeparator6);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem5.setText("Müşteri");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuItem5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem5KeyPressed(evt);
            }
        });
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // menü kısmındaki listele kısmındaki ürüne tıklandığında ürünListele sayfası açılır.
        ürünListele ürün = new ürünListele();
        ürün.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // Yeni bir müşteri listeleme penceresi oluşturdum.
        müsteriListele müsteri = new müsteriListele();

// Müşteri listeleme penceresini görünür yap
        müsteri.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked

    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // menüde ekle kısmındaki ürün kısmına basıldığında ürünSayfası açılır.
        ürünSayfasi ürün = new ürünSayfasi();
        ürün.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Yeni bir müşteri sayfası penceresi oluşturdum.
        müsteriSayfasi müsteri = new müsteriSayfasi();

        // Müşteri sayfası penceresini görünür yaptım.
        müsteri.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // Yeni bir kategorivemarka sayfası penceresi oluşturdum.
        kategoriVeMarka katMar = new kategoriVeMarka();

        // kategorivemarka sayfasi penceresini görünür yaptım.
        katMar.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MouseClicked

    }//GEN-LAST:event_jMenuItem9MouseClicked

    private void hayırCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hayırCheckBoxActionPerformed
        // Yeni bir müşteri sayfası penceresi oluşturdum.
        müsteriSayfasi müsteri = new müsteriSayfasi();

        // Müşteri sayfasi penceresini görünür yaptım.
        müsteri.setVisible(true);
    }//GEN-LAST:event_hayırCheckBoxActionPerformed

    private void evetCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evetCheckBoxActionPerformed
        // Yeni bir müşteri listeleme penceresi oluşturdum.
        müsteriListele müsteri = new müsteriListele();

// Müşteri listeleme penceresini görünür yaptım.
        müsteri.setVisible(true);
    }//GEN-LAST:event_evetCheckBoxActionPerformed

    private void personellisteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personellisteleActionPerformed
        //personel listele butonuna basıldığında personelListele sayfası açılır.
        personelListele personel = new personelListele();
        personel.setVisible(true);

    }//GEN-LAST:event_personellisteleActionPerformed

    private void kalan_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalan_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalan_alaniActionPerformed
    public void fis() {
        // Toplam, ödenen tutar ve kalan değerlerini aldım.
        String toplam = toplam_alani.getText();
        String odenenTutar = odenenTutarAlani.getText();
        String kalan = kalan_alani.getText();

        DefaultTableModel model = (DefaultTableModel) satisTable.getModel();

        model = (DefaultTableModel) satisTable.getModel();

        // Müşteri ve personel bilgilerini, ardından değişim fişi olduğunu belirten bir başlık ekledim
        fisYazdir.setText(fisYazdir.getText() + "Müşterinin Adı ve Soyadı :" + musteriAdiAlani.getText() + "\n");

        fisYazdir.setText(fisYazdir.getText() + "Personel Adı ve Soyadı :" + personelAdiAlani.getText() + "\n");

        fisYazdir.setText(fisYazdir.getText() + "************************************************************\n");

        fisYazdir.setText(fisYazdir.getText() + "          Ürün Değişim Fişidir . Mali Değeri Yoktur .       \n");

        fisYazdir.setText(fisYazdir.getText() + "************************************************************\n");

        // Satış tablosundan alınan ürün adı, fiyat ve adet bilgilerini fişe ekledim.
        fisYazdir.setText(fisYazdir.getText() + "Ürün Adı" + "\t" + "Fiyat" + "\t" + "Adet" + "\n");

        // Döngü ile tablo modelindeki her bir satırdaki verileri fisYazdir alanına eklemek için kullandım.
        for (int i = 0; i < model.getRowCount(); i++) {
            // model.getValueAt(i, 1) ile i. satırın 1. sütunundaki (ürün adı) veriyi alır
            String urun_adi = (String) model.getValueAt(i, 1);

            // model.getValueAt(i, 2) ile i. satırın 2. sütunundaki (fiyat) veriyi alır
            String fiyat = (String) model.getValueAt(i, 2);

            // model.getValueAt(i, 3) ile i. satırın 3. sütunundaki (adet) veriyi alır
            String adet = (String) model.getValueAt(i, 3);

            // fisYazdir alanına mevcut metni alarak, her satır için ürün adı, fiyat ve adet bilgilerini eklemesini sağladım.
            // Bu bilgileri \t  ile ayırır ve yeni satıra geçirdim.
            fisYazdir.setText(fisYazdir.getText() + urun_adi + "\t" + fiyat + "\t" + adet + "\n");

        }

        fisYazdir.setText(fisYazdir.getText() + "\n");
        // Toplam, ödenen tutar ve kalan bilgilerini fişe ekledim.
        fisYazdir.setText(fisYazdir.getText() + "\t" + "\t" + "Toplam :" + toplam + "\n");
        fisYazdir.setText(fisYazdir.getText() + "\t" + "\t" + "Ödenen Tutar :" + odenenTutar + "\n");
        fisYazdir.setText(fisYazdir.getText() + "\t" + "\t" + "Kalan :" + kalan + "\n");
        fisYazdir.setText(fisYazdir.getText() + "\n");
        // Alışverişin tamamlandığını belirten teşekkür mesajını ve veda mesajını fişe ekledim.
        fisYazdir.setText(fisYazdir.getText() + "************************************************************\n");
        fisYazdir.setText(fisYazdir.getText() + "              ALIŞVERİŞİNİZ İÇİN TEŞEKKÜRLER....            \n");
        fisYazdir.setText(fisYazdir.getText() + "                 TEKRARDAN GÖRÜŞMEK ÜZERE                   \n");
        fisYazdir.setText(fisYazdir.getText() + "************************************************************\n");

    }

    private void kalan() {
        // Toplam ve ödenen tutarları aldım ve bunları kalanı hesaplamak için kullandım.
        int toplam = Integer.parseInt(toplam_alani.getText());
        // Ödenen tutardan toplam tutarı çıkararak kalan tutarı buldum.
        int odenenTutar = Integer.parseInt(odenenTutarAlani.getText());

        int kalan = toplam - odenenTutar;
        // Elde edilen kalan tutarı kalan_alani text alanına yazdırdım.
        kalan_alani.setText(String.valueOf(kalan));

    }
    private void yazdırButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yazdırButonuActionPerformed
        kalan();
        fis();
        //fisYazdir butonuna tıkladığımız zaman bütün veriler silinir ve fiş yazdırılır.
        kalan_alani.setText("");
        toplam_alani.setText("");
        odenenTutarAlani.setText("");
        personelAdiAlani.setText("");
        musteriAdiAlani.setText("");
        müsteridi.setText("");
        //tablodaki değerlerde silinir.
        DefaultTableModel model = (DefaultTableModel) satisTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_yazdırButonuActionPerformed

    private void secileniSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secileniSilButonuActionPerformed
        //seçileni sil butonuna basıldığında silinecek metodu çalışır.
        silinecek();
    }//GEN-LAST:event_secileniSilButonuActionPerformed
    private void silinecek() {
        int sum = 0;

        // Tablodaki tüm satırların toplamını hesaplasını için yazdım.
        for (int i = 0; i < satisTable.getRowCount(); i++) {
            sum += Integer.parseInt(satisTable.getValueAt(i, 4).toString());
        }

        int selectedRow = satisTable.getSelectedRow();

        // Eğer hiçbir satır seçilmediyse (-1 döner) .
        if (selectedRow != -1) {
            // Silinecek olan satırın toplam değerini alması için yazdım.
            int silinecekToplam = Integer.parseInt(satisTable.getValueAt(selectedRow, 4).toString());

            // Tablodan seçili satırı kaldırılması için yazdım.
            DefaultTableModel model = (DefaultTableModel) satisTable.getModel();
            model.removeRow(selectedRow);

            // Güncellenmiş toplam değeri hesapladım ve toplam_alani'ni güncelledim
            int yeniToplam = sum - silinecekToplam;
            toplam_alani.setText(Integer.toString(yeniToplam));
        }
    }

    private int stokSorgu(String barkodNo) throws SQLException {
        barkodNo = barkodNo_alani.getText();

        // Veritabanından stok adedini sorgulamak için SQL sorgusu hazırladım.
        String stokSorgu = "SELECT stok_adedi FROM kırtasiye.ürünler WHERE barkod_no = ?";
        try (Connection connection = dbHelper.getConnection(); PreparedStatement stokSorguStatement = connection.prepareStatement(stokSorgu)) {
            // SQL sorgusunda parametre olarak barkod numarasını kullanmasını sağladım.
            stokSorguStatement.setString(1, barkodNo);
            //Sorguyu çalıştırır ve sonucu almayı sağlar.
            ResultSet resultSet = stokSorguStatement.executeQuery();

            // Sonuç kümesinde bir sonraki satır varsa, yani barkod numarasına sahip bir ürün bulunmuşsa,
            if (resultSet.next()) {
                return resultSet.getInt("stok_adedi");
            } else {
                //ürün bulunamazsa -1 değeri döndürür.
                return -1;
            }
        }
    }
    private void ekleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonuActionPerformed
        // Kullanıcıdan girdileri aldım: barkod numarası, ürün adı, fiyat ve adet.
        barkodNo = barkodNo_alani.getText();
        ürün_adi = ürünadi_alani.getText();
        fiyat = fiyat_alani.getText();
        adet = adet_alani.getText();

        //Diğer alanlar barkod numarasını girdiğimizde direkt geliyor ama adet kısmına biz yazacağımız için boş bırakılmaması gerekiyor.Bunun içinde adet alanın boş olup olmadığını kontrol ettim.
        if (adet.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen adeti giriniz. Adet alanı boş bırakılamaz!");
            return;
        }
        // Satırların toplamını hesaplamak için bir değişken tanımladım.
        int sum = 0;

        // Tablodaki tüm satırların toplamını hesaplamasını sağladım.
        for (int i = 0; i < satisTable.getRowCount(); i++) {
            sum += Integer.parseInt(satisTable.getValueAt(i, 4).toString());
        }

        // Girişten alınan fiyat ve adet bilgileri integera dönüştürerek ayrı değişkenlere atanır.
        int fiyatt = Integer.parseInt(fiyat);
        int adett = Integer.parseInt(adet);

        // Yeni toplam hesaplanır ve mevcut toplama eklenmesini sağladım.
        int yeniToplam = fiyatt * adett;
        sum += yeniToplam;

        // Toplam alanına yeni toplam değeri yazılır.
        toplam_alani.setText(Integer.toString(sum));

        try {

            // Stok adedini kontrol etmesini sağladım.
            int stokAdedi = stokSorgu(barkodNo);

            if (stokAdedi == -1) {
                // Ürün bulunamadı, uyarı verir.
                JOptionPane.showMessageDialog(null, "Ürün bulunamadı!");
                return; // İşlemi durdurur.
            }

            if (adett > stokAdedi) {
                // Eğer stok yetersizse , uyarı verir.
                JOptionPane.showMessageDialog(null, "Yetersiz stok! Mevcut stok: " + stokAdedi);
                return; // İşlemi durdurur.
            }

            int yeniStokAdedi = stokAdedi - adett; // Yeni stok adedi hesaplar.
            connection = dbHelper.getConnection();// Veritabanı bağlantısını aldım.

            // Veritabanına satış bilgilerini eklemek için SQL sorgusunu hazırlamasını ve çalıştırmasını sağladım.
            statement = connection.prepareStatement("INSERT INTO kırtasiye.satis(barkod, ürün_adi, fiyat, adet ,toplam) VALUES ( ?, ?, ?, ? ,?)");

            statement.setString(1, barkodNo);
            statement.setString(2, ürün_adi);
            statement.setString(3, fiyat);
            statement.setString(4, adet);
            statement.setInt(5, yeniToplam);
            statement.executeUpdate();

            // Stok adedini güncellemek için sql ifadesi yazdım.
            String stokGuncelle = "UPDATE kırtasiye.ürünler SET stok_adedi = ? WHERE barkod_no = ?";
            PreparedStatement stokGuncelleStatement = connection.prepareStatement(stokGuncelle);
            stokGuncelleStatement.setInt(1, yeniStokAdedi);
            stokGuncelleStatement.setString(2, barkodNo);
            stokGuncelleStatement.executeUpdate();

            // Metin alanlarını temizlesini sağladım.
            barkodNo_alani.setText("");
            ürünadi_alani.setText("");
            fiyat_alani.setText("");
            adet_alani.setText("");

        } catch (SQLException ex) {
            // Herhangi bir SQL hatası durumunda hata mesajını gösterir.
            dbHelper.ShowError(ex);
        }

        // Satış tablosuna yeni bir satır eklemek için veri modelini güncellemesi için oluşturdum.
        DefaultTableModel model = (DefaultTableModel) satisTable.getModel();
        Object[] rowData = {barkodNo, ürün_adi, fiyat, adet, yeniToplam};
        model.addRow(rowData);


    }//GEN-LAST:event_ekleButonuActionPerformed

    private void satisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satisTableMouseClicked

    }//GEN-LAST:event_satisTableMouseClicked

    private void urunlisteleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunlisteleButonuActionPerformed
        //Ürün Listele butonuna basıldığında ürünListele sayfası açılır.
        ürünListele urun = new ürünListele();
        urun.setVisible(true);
    }//GEN-LAST:event_urunlisteleButonuActionPerformed

    private void barkodNo_alaniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barkodNo_alaniKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Enter tuşuna basıldığında barkod numarasını alması için yazdım.
            String barkod = barkodNo_alani.getText();
            try {
                connection = dbHelper.getConnection();// Veritabanı bağlantısını almalı.
                // Bağlantı alınamazsa
                if (connection == null) {
                    // Kullanıcıya hata mesajı gösterir.
                    JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı.");
                    return; // Metodu sonlandır
                }
                // Veritabanından ürünü barkod numarasına göre sorguladım.
                statement = connection.prepareStatement("SELECT * FROM kırtasiye.ürünler WHERE barkod_no = ?");
                statement.setString(1, barkod);
                resultSet = statement.executeQuery();

                // Ürün bulunamazsa
                if (!resultSet.next()) {
                    // Kullanıcıya hata mesajı gösterir.
                    JOptionPane.showMessageDialog(this, "Ürün kodu bulunamadı.");
                } else {
                    // Ürün bulunursa ürün adı ve fiyatını ilgili alanlara yazması için kullandım.
                    String urun_adı = resultSet.getString("ürün_adi");
                    String fiyat = resultSet.getString("fiyat");
                    ürünadi_alani.setText(urun_adı.trim());
                    fiyat_alani.setText(fiyat.trim());
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Veritabanı sorgulanırken bir hata oluştu.");
            }
        }
    }//GEN-LAST:event_barkodNo_alaniKeyPressed

    private void barkodNo_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barkodNo_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barkodNo_alaniActionPerformed

    private void müsteridiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_müsteridiActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_müsteridiActionPerformed

    private void müsteridiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteridiKeyPressed

// Enter tuşuna basıldığında müşteri kimlik numarasını alır.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String id = müsteridi.getText();
            try {
                connection = dbHelper.getConnection();
                // Bağlantı alınamazsa
                if (connection == null) {
                    // Kullanıcıya hata mesajı gösterir.
                    JOptionPane.showMessageDialog(this, "Veritabanı bağlantısı kurulamadı.");
                    return; // Metodu sonlandır
                }
                // Veritabanından müşteriyi sorgular.
                statement = connection.prepareStatement("SELECT * FROM kırtasiye.müsteri WHERE id = ?");
                statement.setString(1, id);
                resultSet = statement.executeQuery();

                // Müşteri bulunamazsa
                if (!resultSet.next()) {
                    // Kullanıcıya hata mesajı gösterir.
                    JOptionPane.showMessageDialog(this, "Müşteri kodu bulunamadı.");
                } else {
                    // Müşteri bulunursa ad ve soyadını ilgili alana yazması için kullandım.
                    String ad = resultSet.getString("ad");
                    String soyad = resultSet.getString("soyad");
                    musteriAdiAlani.setText(ad + " " + soyad);// ad ve soyad ikisinin de gözükmesi için bu şekilde yazdım.
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Veritabanı sorgulanırken bir hata oluştu.");
            }
        }


    }//GEN-LAST:event_müsteridiKeyPressed

    private void adet_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adet_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adet_alaniActionPerformed

    private void jMenuItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem1KeyPressed
        //Ctrl+B tuşuna basıldığında müsteriSayfası açılır.
        if (evt.getKeyCode() == KeyEvent.VK_B) {
            müsteriSayfasi müsteri = new müsteriSayfasi();
            müsteri.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem1KeyPressed

    private void jMenuItem10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem10KeyPressed
        //Ctrl+E tuşuna basıldığında ürünSayfası açılır.
        if (evt.getKeyCode() == KeyEvent.VK_E) {
            ürünSayfasi urun = new ürünSayfasi();
            urun.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem10KeyPressed

    private void jMenuItem9MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuItem9MenuKeyPressed

    }//GEN-LAST:event_jMenuItem9MenuKeyPressed

    private void jMenu3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu3KeyPressed
        //Shift+9 tuşuna basıldığında ürünListele sayfası açılır.
        if (evt.getKeyCode() == KeyEvent.VK_9) {
            ürünListele urun = new ürünListele();
            urun.setVisible(true);

        }
    }//GEN-LAST:event_jMenu3KeyPressed

    private void jMenuItem5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem5KeyPressed
        //Shift+8 tuşuna basıldığında müsteriListele sayfası açılır.
        if (evt.getKeyCode() == KeyEvent.VK_8) {
            müsteriListele müsteri = new müsteriListele();
            müsteri.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem5KeyPressed

    private void jMenu4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu4KeyPressed

    }//GEN-LAST:event_jMenu4KeyPressed

    private void jMenuItem9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem9KeyPressed
        //Ctrl+H tuşuna basıldığında kategoriVeMarka sayfası açılır.
        if (evt.getKeyCode() == KeyEvent.VK_H) {
            kategoriVeMarka katMar = new kategoriVeMarka();
            katMar.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem9KeyPressed

    private void satisGecmisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisGecmisiActionPerformed
        //Satış geçmişi butonuna basıldığında satisGecmisi sayfası açılır.
        satisGecmisi satis = new satisGecmisi();
        satis.setVisible(true);
    }//GEN-LAST:event_satisGecmisiActionPerformed

    private void tamamlandıButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamamlandıButonuActionPerformed
        //ödeme yapıldığında anaekrandaki fiş kısmı da silinsin diye kullandım.
        fisYazdir.setText("");

    }//GEN-LAST:event_tamamlandıButonuActionPerformed

    private void ürünadi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürünadi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ürünadi_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adet_alani;
    private javax.swing.JTextField barkodNo_alani;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton ekleButonu;
    private javax.swing.JCheckBox evetCheckBox;
    private javax.swing.JTextArea fisYazdir;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JCheckBox hayırCheckBox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField kalan_alani;
    private javax.swing.JTextField musteriAdiAlani;
    private javax.swing.JTextField müsteridi;
    private javax.swing.JTextField odenenTutarAlani;
    private javax.swing.JTextField personelAdiAlani;
    private javax.swing.JButton personellistele;
    private javax.swing.JButton satisGecmisi;
    private javax.swing.JTable satisTable;
    private javax.swing.JButton secileniSilButonu;
    private javax.swing.JButton tamamlandıButonu;
    private javax.swing.JTextField toplam_alani;
    private javax.swing.JButton urunlisteleButonu;
    private javax.swing.JButton yazdırButonu;
    private javax.swing.JTextField ürünadi_alani;
    // End of variables declaration//GEN-END:variables
}
