package kırtasiyeotomasyonuu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;

public class kayıtOl extends javax.swing.JFrame {

    Connection connect = null;
    DbHelper db = new DbHelper();
    PreparedStatement statement = null; // SQL sorgusunu çalıştırmak için gerekli olan class
    ResultSet resultSet = null;
    private User user;

    public kayıtOl() {
        initComponents();
        // iki seçenek aynı anda seçilmesin diye ekledim.
        buttonGroup1.add(erkekButton);
        buttonGroup1.add(kadınButton);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    public void ekle() throws SQLException {

        try {

            connect = db.getConnection();

            //Aynı kullanıcıya hata vermesi için : 
            // Veritabanından "kırtasiye" şemasındaki "giris" tablosundan belirli bir kullanıcı adına göre veri seçer.
            // "?" yerine kullanıcı tarafından girilen kullanıcı adını parametre olarak kullanır.                
            statement = connect.prepareStatement("select * from kırtasiye.giris where Kullanici_adi=?");
            // Kullanıcı tarafından girilen kullanıcı adını SQL sorgusuna parametre olarak ekler.
            statement.setString(1, KullaniciAdiAlani.getText());
            // Sorguyu çalıştır ve sonuçları resultSet değişkenine atar.
            resultSet = statement.executeQuery();

            //Daha okunacak veri var mı ? 
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(null, "Girdiğiniz Kullanıcı Adı Kayıtlı! Lütfen Farklı Bir Kullanıcı Adı Giriniz.");

            } else {

                // Yeni kullanıcı veritabanına ekleme işlemi gerçekleştirilir.
                String sql = "insert into kırtasiye.giris(AdSoyad,Email,Kullanici_adi,Sifre) values(?,?,?,?)";
                statement = connect.prepareStatement(sql);

                // İlk yer tutucusu (1. sıradaki '?') 'AdSoyad' değişkeniyle doldurmasını sağladım.
                statement.setString(1, user.getAdvesoyad());

                // İlk yer tutucusu (1. sıradaki '?') 'Email' değişkeniyle doldurmasını sağladım.
                statement.setString(2, user.getEmail());

                // İlk yer tutucusu (1. sıradaki '?') 'Kullanici_adi' değişkeniyle doldurmasını sağladım.
                statement.setString(3, user.getKullanici_adi());

                // İlk yer tutucusu (1. sıradaki '?') 'Sifre' değişkeniyle doldurmasını sağladım.
                statement.setString(4, user.getParola());
                statement.executeUpdate();// sql komutu veritabanında çalıştırılır.
                JOptionPane.showMessageDialog(null, "KAYIT BAŞARIYLA EKLENDİ.");
            }
        } catch (SQLException ex) {
            db.ShowError(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        uyeKayıtFormu = new javax.swing.JLabel();
        ad_soyad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullanici_adi = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adSoyadAlani = new javax.swing.JTextField();
        KullaniciAdiAlani = new javax.swing.JTextField();
        email_alani = new javax.swing.JTextField();
        sifre_alani = new javax.swing.JPasswordField();
        kayıt_butonu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kadınButton = new javax.swing.JRadioButton();
        erkekButton = new javax.swing.JRadioButton();
        advesoyadLabel = new javax.swing.JLabel();
        kullaniciAdiLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();
        cinsiyetLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uyeKayıtFormu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        uyeKayıtFormu.setText("ÜYE KAYIT FORMU");

        ad_soyad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ad_soyad.setText("Ad ve Soyad :");

        kullanici_adi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kullanici_adi.setText("Kullanıcı Adı :");

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Şifre:");

        adSoyadAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adSoyadAlaniKeyReleased(evt);
            }
        });

        email_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_alaniActionPerformed(evt);
            }
        });

        kayıt_butonu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kayıt_butonu.setForeground(new java.awt.Color(204, 0, 51));
        kayıt_butonu.setText("KAYIT OL ");
        kayıt_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıt_butonuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cinsiyet : ");

        kadınButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kadınButton.setText("Kadın");

        erkekButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        erkekButton.setText("Erkek ");

        advesoyadLabel.setForeground(new java.awt.Color(204, 0, 51));

        kullaniciAdiLabel.setForeground(new java.awt.Color(204, 0, 51));

        emailLabel.setForeground(new java.awt.Color(204, 0, 51));

        sifreLabel.setForeground(new java.awt.Color(204, 0, 51));

        cinsiyetLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(uyeKayıtFormu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(kayıt_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ad_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kullanici_adi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adSoyadAlani)
                                    .addComponent(KullaniciAdiAlani)
                                    .addComponent(email_alani)
                                    .addComponent(sifre_alani)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kadınButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(erkekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advesoyadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sifreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cinsiyetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(uyeKayıtFormu)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advesoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ad_soyad)
                        .addComponent(adSoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kullanici_adi)
                        .addComponent(KullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email)
                        .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kadınButton)
                    .addComponent(erkekButton)
                    .addComponent(jLabel3)
                    .addComponent(cinsiyetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sifre_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addComponent(kayıt_butonu)
                .addGap(22, 22, 22))
        );

        kadınButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_alaniActionPerformed

    }//GEN-LAST:event_email_alaniActionPerformed

    private void kayıt_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıt_butonuActionPerformed
        if (KullaniciAdiAlani.getText().trim().isEmpty() || sifre_alani.getText().trim().isEmpty() || email_alani.getText().trim().isEmpty() || adSoyadAlani.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");
        } else {
            // Ad ve soyadın doğruluğunu kontrol etmek için :
            Pattern pAdVeSoyad = Pattern.compile("[a-zA-Z]+\\s+[a-zA-Z]+");
            // Oluşturulan desen, adSoyadAlani'ndaki metinle eşleştirilmesi için kullandım.
            Matcher mAdVeSoyad = pAdVeSoyad.matcher(adSoyadAlani.getText());

            // Kullanıcı adının doğruluğunu kontrol etmek için :Sadece küçük harf (a-z), büyük harf (A-Z), rakam (0-9) veya alt çizgi (_) karakterlerinden oluşmalıdır.
            Pattern pKullaniciAdi = Pattern.compile("[a-zA-Z0-9_]+");
            Matcher mKullaniciAdi = pKullaniciAdi.matcher(KullaniciAdiAlani.getText());

            // Email adresinin doğruluğunu kontrol etmek için :
            Pattern pMail = Pattern.compile("\\w+@\\w+\\.\\w+");
            Matcher mMail = pMail.matcher(email_alani.getText());

            // Şifre doğruluğunu kontrol etmek için :
            Pattern pSifre = Pattern.compile("[0-9]+");
            Matcher mSifre = pSifre.matcher(sifre_alani.getText());

            //radiobutonunun ikisi de seilmezse verilcek hata :
            if (!kadınButton.isSelected() && !erkekButton.isSelected()) {
                cinsiyetLabel.setText("Lütfen cinsiyetinizi seçiniz!");
                // Eğer şifre metni desenle eşleşmiyorsa:
            } else if (!mSifre.matches()) {
                // Şifre etiketine uygun bir hata mesajı atanıyor.
                sifreLabel.setText("Şifreniz sadece rakamlardan oluşmalıdır.");
            } else if (!mAdVeSoyad.matches()) {
                advesoyadLabel.setText("Geçersiz ad ve soyad girdiniz.Türkçe karakter kullanmayınız...");
            } else if (!mKullaniciAdi.matches()) {
                sifreLabel.setText("Kullanıcı adınız sadece harflerden  , rakamlardan veya alt çizgiden oluşmalıdır.(kullanici123,Kullanici_Adi)");
            } else if (!mMail.matches()) {
                emailLabel.setText("Hatalı email adresi girdiniz.Örnek : email@gmail.com");
                // Diğer durumlarda (tüm girişler geçerliyse):
            } else {
                // Tüm bilgiler doğruysa, önceki uyarıları temizler.           
                advesoyadLabel.setText(null);
                kullaniciAdiLabel.setText(null);
                emailLabel.setText(null);
                sifreLabel.setText(null);
                try {
                    // Kullanıcı nesnesi oluşturdum ve veritabanına ekledim.
                    user = new User(adSoyadAlani.getText(), email_alani.getText(), KullaniciAdiAlani.getText(), new String(sifre_alani.getPassword()));
                    ekle();// Kullanıcı veritabanına eklenmesini sağladım.
                    //Giriş ekranını açar .
                    kırtasiye_giris giris = new kırtasiye_giris();
                    giris.setVisible(true);
                } catch (SQLException ex) {
                    db.ShowError(ex);

                }
            }
        }

    }//GEN-LAST:event_kayıt_butonuActionPerformed

    private void adSoyadAlaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adSoyadAlaniKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_adSoyadAlaniKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayıtOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayıtOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayıtOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayıtOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayıtOl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KullaniciAdiAlani;
    private javax.swing.JTextField adSoyadAlani;
    private javax.swing.JLabel ad_soyad;
    private javax.swing.JLabel advesoyadLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cinsiyetLabel;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField email_alani;
    private javax.swing.JRadioButton erkekButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton kadınButton;
    private javax.swing.JButton kayıt_butonu;
    private javax.swing.JLabel kullaniciAdiLabel;
    private javax.swing.JLabel kullanici_adi;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JPasswordField sifre_alani;
    private javax.swing.JLabel uyeKayıtFormu;
    // End of variables declaration//GEN-END:variables
}
