/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kırtasiyeotomasyonuu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pars
 */
public class müsteriSayfasi extends javax.swing.JFrame {

    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    PreparedStatement statement = null;
    ResultSet resultSet = null;

    public müsteriSayfasi() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Ana sayfanın kapatılmasını önlemek için

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ekleButonu = new javax.swing.JButton();
        soyad_alani = new javax.swing.JTextField();
        ad_alani = new javax.swing.JTextField();
        mail_alani = new javax.swing.JTextField();
        telefonNo_alani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefon No :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mail:");

        ekleButonu.setText("Ekle");
        ekleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MÜŞTERİ EKLEME");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ekleButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(soyad_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ad_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(mail_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(telefonNo_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ekleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(soyad_alani)
                                    .addComponent(telefonNo_alani)
                                    .addComponent(mail_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ad_alani))))
                        .addGap(14, 14, 14)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefonNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(ekleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void ekle() {
        // Kullanıcı tarafından girilen müşteri bilgilerini almasını sağladım.
        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String telefonNo = telefonNo_alani.getText();
        String mail = mail_alani.getText();

        try {
            connection = dbHelper.getConnection();
            // Veritabanına müşteri eklemek için SQL sorgusu hazırladım.
            statement = connection.prepareStatement("INSERT INTO kırtasiye.müsteri(ad, soyad, telefon_no, mail) VALUES ( ?, ?, ?, ?)");

            // SQL sorgusundaki yer tutucularına gerçek değerleri atadım.
            statement.setString(1, ad);
            statement.setString(2, soyad);
            statement.setString(3, telefonNo);
            statement.setString(4, mail);
            statement.executeUpdate();  // SQL sorgusunu veritabanına göndermesini ve müşteriyi eklemesini sağladım.
            JOptionPane.showMessageDialog(null, "Müşteri başarıyla eklendi.");

        } catch (SQLException ex) {
            dbHelper.ShowError(ex);

        }

    }
    private void ekleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonuActionPerformed
        // Metin alanlarının boş olup olmadığını kontrol ettim.
        if (ad_alani.getText().trim().isEmpty() || soyad_alani.getText().trim().isEmpty() || telefonNo_alani.getText().trim().isEmpty() || mail_alani.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");
        } else {
            // Ad için doğrulama: İki veya tek isim olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pAd = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mAd = pAd.matcher(ad_alani.getText());

            // Soyad için doğrulama: İki veya tek soyad olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pSoyad = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mSoyad = pSoyad.matcher(soyad_alani.getText());

            // Email için doğrulama:
            Pattern pMail = Pattern.compile("\\w+@\\w+\\.\\w+");
            Matcher mMail = pMail.matcher(mail_alani.getText());

            // Telefon numarası için doğrulama(05*********)
            Pattern pTelefonNo = Pattern.compile("0[0-9]{10}");
            Matcher mTelefonNo = pTelefonNo.matcher(telefonNo_alani.getText());

            // Telefon numarası geçerli değilse, kullanıcıya uyarı vermeli.
            if (!mTelefonNo.matches()) {
                JOptionPane.showMessageDialog(this, "Hatalı telefon numarası girdiniz.(05*********)");

                // Soyad geçerli değilse, kullanıcıya uyarı vermeli.
            } else if (!mSoyad.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz soyad girdiniz . Soyad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");

                // Ad geçerli değilse, kullanıcıya uyarı vermeli.
            } else if (!mAd.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz ad girdiniz . Ad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");

                // Email geçerli değilse, kullanıcıya uyarı vermeli.
            } else if (!mMail.matches()) {
                JOptionPane.showMessageDialog(this, "Hatalı email adresi girdiniz.( email@gmail.com");
            } else {
                // Tüm girdiler geçerli ise, ekleme işlemini gerçekleştirir.
                ekle();
            }

        }
      
    }//GEN-LAST:event_ekleButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(müsteriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(müsteriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(müsteriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(müsteriSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new müsteriSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JButton ekleButonu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mail_alani;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField telefonNo_alani;
    // End of variables declaration//GEN-END:variables
}
