/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kırtasiyeotomasyonuu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pars
 */
public class müsteriListele extends javax.swing.JFrame {

    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    PreparedStatement statement = null;
    ResultSet resultSet = null;

    public müsteriListele() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Ana sayfanın kapatılmasını önlemek için

    }

    private void müsteriListeleme() throws SQLException {

        connection = dbHelper.getConnection();
        //Müşteri tablosundaki verileri tutmak için oluşturduğum model :
        DefaultTableModel model = (DefaultTableModel) müsteriTable.getModel();
        model.setRowCount(0); //Tekrarlanan verilerin önüne geçilmesini sağlamak için kullandım.

        try {
            //tüm müşterileri yazdırmak için sql ifadesini böyle kullandım.
            statement = connection.prepareStatement("SELECT * FROM kırtasiye.müsteri");
            resultSet = statement.executeQuery();

            while (resultSet.next()) {

                Object[] row = new Object[müsteriTable.getColumnCount()]; // müşteri tablosundaki sütun sayısı kadar yeni bir Object dizisi oluşturdum.
                // resultSetten gelen verileri alır ve bunları satırlara  eklemesi için :
                row[0] = resultSet.getString("id"); // sonuç kümesindeki id  sütun verileri alınıp satır  dizisine eklemesini sağladım.
                row[1] = resultSet.getString("ad");
                row[2] = resultSet.getString("soyad");
                row[3] = resultSet.getString("telefon_no");
                row[4] = resultSet.getString("mail");
                model.addRow(row);// oluşan satırı modele eklemek için kullandım
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        ad_alani = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        telefonNo_alani = new javax.swing.JTextField();
        mail_alani = new javax.swing.JTextField();
        güncelleButonu = new javax.swing.JButton();
        silButonu = new javax.swing.JButton();
        listeleButonu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        müsteriTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ad :");

        jLabel2.setText("Soyad :");

        jLabel3.setText("Telefon No : ");

        jLabel4.setText("Mail : ");

        güncelleButonu.setText("Güncelle ");
        güncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleButonuActionPerformed(evt);
            }
        });

        silButonu.setText("Sil");
        silButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButonuActionPerformed(evt);
            }
        });

        listeleButonu.setText("Listele");
        listeleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeleButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ad_alaniLayout = new javax.swing.GroupLayout(ad_alani);
        ad_alani.setLayout(ad_alaniLayout);
        ad_alaniLayout.setHorizontalGroup(
            ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_alaniLayout.createSequentialGroup()
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(ad_alaniLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(add_alani)
                                .addComponent(soyad_alani)
                                .addComponent(telefonNo_alani)
                                .addComponent(mail_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                        .addGroup(ad_alaniLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(silButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addComponent(güncelleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ad_alaniLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(listeleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        ad_alaniLayout.setVerticalGroup(
            ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_alaniLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(add_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(telefonNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(mail_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ad_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(güncelleButonu)
                    .addComponent(silButonu))
                .addGap(18, 18, 18)
                .addComponent(listeleButonu)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        müsteriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "Telefon No ", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        müsteriTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                müsteriTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(müsteriTable);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MÜŞTERİ LİSTELEME ");

        jDesktopPane1.setLayer(ad_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void guncelle() {
        try {
            connection = dbHelper.getConnection();
            // Tablo modelinden seçilen satırın indeksini almak için kullandım.
            DefaultTableModel model = (DefaultTableModel) müsteriTable.getModel();
            int selectedIndex = müsteriTable.getSelectedRow();

            // seçilen lomüşterinin idsini aldım.
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

            // yeni müşteri bilgileri almak için ekledim.
            String yeniAd, yeniSoyad, yeniTelefon, yeniMail;
            yeniAd = add_alani.getText();
            yeniSoyad = soyad_alani.getText();
            yeniTelefon = telefonNo_alani.getText();
            yeniMail = mail_alani.getText();

            //güncelleme için sql ifadesi oluşturdum.
            statement = connection.prepareStatement("update kırtasiye.müsteri set ad=?,soyad=?,telefon_no=?,mail=? where id=?");

            // sql ifadesindeki soru işaretinin (?) yerlerini doldurmak için oluşturdum.
            statement.setString(1, yeniAd);
            statement.setString(2, yeniSoyad);
            statement.setString(3, yeniTelefon);
            statement.setString(4, yeniMail);
            statement.setInt(5, id);
            //güncelleme sorgusunu veri tabanına göndermek için kullandım.
            statement.executeUpdate();

            // Güncellenmiş veriyi tabloya yansıtmak için ilgili satırı doğrudan güncelleyebilmek için kullandığım yöntem :
            model.setValueAt(yeniAd, selectedIndex, 1);
            model.setValueAt(yeniSoyad, selectedIndex, 2);
            model.setValueAt(yeniTelefon, selectedIndex, 3);
            model.setValueAt(yeniMail, selectedIndex, 4);
            JOptionPane.showMessageDialog(this, " Müşteri Güncellendi.");

            add_alani.setText("");
            soyad_alani.setText("");
            telefonNo_alani.setText("");
            mail_alani.setText("");

        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }
    }
    private void güncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleButonuActionPerformed
        //Boş alan kontrolü oluşturdum.
        if (add_alani.getText().trim().isEmpty() || soyad_alani.getText().trim().isEmpty() || telefonNo_alani.getText().trim().isEmpty() || mail_alani.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

            // Alanlar doluysa, girilen verilerin doğruluğunu kontrol etmeli.
        } else {

            // Ad için doğrulama: İki veya tek isim olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pAd = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mAd = pAd.matcher(add_alani.getText());

            // Soyad için doğrulama: İki veya tek soyad olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pSoyad = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mSoyad = pSoyad.matcher(soyad_alani.getText());

            // Email için doğrulama
            Pattern pMail = Pattern.compile("\\w+@\\w+\\.\\w+");
            Matcher mMail = pMail.matcher(mail_alani.getText());

            // Telefon numarası için doğrulama (05*********)
            Pattern pTelefonNo = Pattern.compile("0[0-9]{10}");
            Matcher mTelefonNo = pTelefonNo.matcher(telefonNo_alani.getText());

            if (!mTelefonNo.matches()) {
                // Telefon numarası geçerli değilse, kullanıcıya uyarı vermeli
                JOptionPane.showMessageDialog(this, "Hatalı telefon numarası girdiniz.(05*********)");
                // Soyad geçerli değilse, kullanıcıya uyarı vermeli
            } else if (!mSoyad.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz soyad giriniz . Soyad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");
                // Ad geçerli değilse, kullanıcıya uyarı vermeli
            } else if (!mAd.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz ad giriniz . Ad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");
                // Email geçerli değilse, kullanıcıya uyarı vermeli
            } else if (!mMail.matches()) {
                JOptionPane.showMessageDialog(this, "Hatalı email adresi girdiniz.( email@gmail.com");
            } else {
                // Tüm girdiler geçerli ise, güncelleme işlemini gerçekleştirmeli.
                guncelle();
            }

        }


    }//GEN-LAST:event_güncelleButonuActionPerformed

    private void listeleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeleButonuActionPerformed
        try {
            müsteriListeleme();
        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }
    }//GEN-LAST:event_listeleButonuActionPerformed

    private void silButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButonuActionPerformed
        if (add_alani.getText().trim().isEmpty() || soyad_alani.getText().trim().isEmpty() || telefonNo_alani.getText().trim().isEmpty() || mail_alani.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen Tablodan Listeleme Yapıp Belirli Bir Satır Seçip Öyle Silme İşlemi Yapın");
        } else {
            try {
                connection = dbHelper.getConnection();

                // Tablo modelinden seçilen satırın indeksini ve müşteri ID'sini almak için oluşturdum.
                DefaultTableModel model = (DefaultTableModel) müsteriTable.getModel();
                int selectedIndex = müsteriTable.getSelectedRow();
                int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

                // Veritabanından müşteriyi silmek için SQL sorgusu oluşturdum.
                statement = connection.prepareStatement("DELETE FROM kırtasiye.müsteri WHERE id=?");
                statement.setInt(1, id);
                // SQL sorgusunu veritabanına göndermek için kullandım.
                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, add_alani.getText() + " İsimli Müşteri Silindi.");

                // Tablodan seçilen satırı ve ilgili verileri kaldırmak için kullandım.
                model.removeRow(selectedIndex);

                add_alani.setText("");
                soyad_alani.setText("");
                telefonNo_alani.setText("");
                mail_alani.setText("");

            } catch (SQLException ex) {
                dbHelper.ShowError(ex);
            }
        }
    }//GEN-LAST:event_silButonuActionPerformed

    private void müsteriTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_müsteriTableMouseClicked
        // Tablo modelinden seçilen satırın verilerini alıp textFieldlara yazdırmak için oluşturdum.

        DefaultTableModel model = (DefaultTableModel) müsteriTable.getModel();

        // Tablodan seçilen satırın indeksini bulmalı.
        int selectedIndex = müsteriTable.getSelectedRow();

        // Seçilen satırdaki müşterinin ID'sini almalı.
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

        // Seçilen satırdaki müşterinin adını al ve ilgili alanı doldurmak için kullandım.
        add_alani.setText(model.getValueAt(selectedIndex, 1).toString());

        // Seçilen satırdaki müşterinin soyadını al ve ilgili alanı doldurmak için kullandım.
        soyad_alani.setText(model.getValueAt(selectedIndex, 2).toString());

        // Seçilen satırdaki telefon numarasını al ve ilgili alanı doldurmak için kullandım.
        telefonNo_alani.setText(model.getValueAt(selectedIndex, 3).toString());

        // Seçilen satırdaki mail adresini al ve ilgili alanı doldurmak için kullandım.
        mail_alani.setText(model.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_müsteriTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(müsteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(müsteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(müsteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(müsteriListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new müsteriListele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ad_alani;
    private javax.swing.JTextField add_alani;
    private javax.swing.JButton güncelleButonu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listeleButonu;
    private javax.swing.JTextField mail_alani;
    private javax.swing.JTable müsteriTable;
    private javax.swing.JButton silButonu;
    private javax.swing.JTextField soyad_alani;
    private javax.swing.JTextField telefonNo_alani;
    // End of variables declaration//GEN-END:variables
}
