/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kırtasiyeotomasyonuu;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class personelListele extends javax.swing.JFrame {

    // Diğer gerekli ayarlamaları yapabilirsiniz
// Bir personel nesnesini temsil eden bir sınıf tanımladım.
    private String ad;
    private String soyad;
    private double maas;

    public personelListele(String ad, String soyad, double maas) {
        // Parametreler, sınıfın özelliklerine atadım.
        this.ad = ad;
        this.soyad = soyad;
        this.maas = maas;
    }

    public String getAd() {
        return ad;
    }

    public void setAd(String ad) {
        this.ad = ad;
    }

    public String getSoyad() {
        return soyad;
    }

    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }

    public double getMaas() {
        return maas;
    }

    public void setMaas(double maas) {
        this.maas = maas;
    }

    public personelListele() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Ana sayfanın kapatılmasını önlemek için
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        maas_alani = new javax.swing.JTextField();
        dosyadanListele = new javax.swing.JButton();
        dosyayaEkle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTablosu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        isimListesi = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maaş :");

        soyad_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyad_alaniActionPerformed(evt);
            }
        });

        dosyadanListele.setText("Dosyadan Listele");
        dosyadanListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyadanListeleActionPerformed(evt);
            }
        });

        dosyayaEkle.setText("Dosyaya Ekle");
        dosyayaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyayaEkleActionPerformed(evt);
            }
        });

        personelTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Soyad", "Maaş"
            }
        ));
        jScrollPane1.setViewportView(personelTablosu);

        jScrollPane2.setViewportView(isimListesi);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PERSONEL LİSTELEME ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PERSONELLER");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ad_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(soyad_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(maas_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dosyadanListele, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dosyayaEkle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(dosyayaEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(dosyadanListele))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(maas_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(soyad_alani)))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(ad_alani)))))
                        .addGap(39, 39, 39)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79)))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(132, 132, 132))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosyayaEkle)
                            .addComponent(dosyadanListele)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void dosyayaEkle() {
        // "personel.txt" adında bir dosya oluşturdum.
        File file = new File("personel.txt");

        //Dosyanın var olup olmadığını kontrol ettim .
        if (!file.exists()) {
            System.out.println("Dosya bulunamadı.");
            return;
        }
        try {
            // Metin alanlarından giriş değerleri alması için oluşturdum.
            ad = ad_alani.getText();
            soyad = soyad_alani.getText();

            // Maaş alanından alınan metin, double türüne dönüştürdüm.
            maas = Double.parseDouble(maas_alani.getText());

            // Dosyaya yazma işlemi için FileWriter ve BufferedWriter oluşturdum.
            FileWriter fwriter = new FileWriter(file, true);
            BufferedWriter bWriter = new BufferedWriter(fwriter);
            bWriter.write(ad + "," + soyad + "," + maas);

            // yeni bir satıra geçsin diye yazdım.
            bWriter.newLine();

            //dosyayı kapatmak için kullandım .
            bWriter.close();

            ad_alani.setText("");
            soyad_alani.setText("");
            maas_alani.setText("");

            JOptionPane.showMessageDialog(this, ad + " isimli personel eklenmiştir.");
        } catch (IOException ex) {
            System.err.println("Dosya yazma hatası: " + ex.getMessage());

        }
    }
    private void dosyayaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyayaEkleActionPerformed

        // Alanların dolu olup olmadığını kontrol etmesini sağladım.
        if (ad_alani.getText().isEmpty() || soyad_alani.getText().isEmpty() || maas_alani.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen ad, soyad ve maaş alanlarını doldurun.");
            return;
        } else {

              // Ad için doğrulama: İki veya tek isim olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pAd = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mAd = pAd.matcher(ad_alani.getText());

           // Soyad için doğrulama: İki veya tek soyad olabilir .Sadece harflerden oluşmalı, Türkçe karakter içermemeli
            Pattern pSoyad = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher mSoyad = pSoyad.matcher(soyad_alani.getText());

            // Maaş için doğrulama : 
            Pattern pmaas = Pattern.compile("\\d+");
            Matcher mmaas = pmaas.matcher(maas_alani.getText());

            if (!mmaas.matches()) {
                // Maaş  geçerli değilse, kullanıcıya uyarı vermeli
                JOptionPane.showMessageDialog(this, "Hatalı telefon numarası girdiniz.(05*********)");
                // Soyad geçerli değilse, kullanıcıya uyarı vermeli
            } else if (!mSoyad.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz soyad giriniz . Soyad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");
                // Ad geçerli değilse, kullanıcıya uyarı vermeli
            } else if (!mAd.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz ad giriniz . Ad sadece harflerden oluşmaktadır . Türkçe karakter kullanmayınız.");

            } else {
                dosyayaEkle();
            }
        }
    }//GEN-LAST:event_dosyayaEkleActionPerformed

    private void dosyadanListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyadanListeleActionPerformed
        File file = new File("personel.txt");
        if (!file.exists()) {
            System.out.println("Dosya bulunamadı.");
            return;
        }
// Tablo modeli oluşturdum.
        DefaultTableModel model = (DefaultTableModel) personelTablosu.getModel();
        model.setRowCount(0); //Tabloya her zaman en güncel veriler eklenmesini  ve tekrarlanan verilerin önüne geçilmesini sağlamak için kullandım.

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;

            //Dosya satır satır okunuyor mu ? ona bakmak için yazdım.
            while ((line = reader.readLine()) != null) {

                //Satır virgüllerle ayrıldığı için virgülsüz kısımları da bizi ilgilendirdiği için kullandım.
                String[] parts = line.split(",");

                //Eğer satırın 3 parçası (ad,soyad,maas) da varsa eksik yoksa , yeni satır oluşturur .
                if (parts.length == 3) {
                    String ad = parts[0];
                    String soyad = parts[1];
                    double maas = Double.parseDouble(parts[2]);

                    Object[] row = {ad, soyad, maas}; //yeni satır oluşturur.
                    model.addRow(row); // Yeni verileri tabloya ekler
                    listeEkle(); // personel ad ve soyadı listeye eklemek için metot yazdım.
                } else {
                    System.out.println("Hatalı format: " + line);
                }
            }
        } catch (IOException | NumberFormatException e) {
            System.err.println("Dosya okuma hatası: " + e.getMessage());
        }
    }

    private void listeEkle() {
        // Personel isimlerini tutmak için bir DefaultListModel oluşturdum.
        DefaultListModel<String> personelModel = new DefaultListModel<>();

        // Personel tablosundan veri almak için bir DefaultTableModel oluşturdum.
        DefaultTableModel model = (DefaultTableModel) personelTablosu.getModel();

        int maasColumnIndex = 2; // Maas sütununun indeksi
        int soyadColumnIndex = 1; //  Adet sütununun indeksi
        int adColumnIndex = 0; // Ad sütununun indeksi

        // Tüm satırları dönerek JList'e eklemesi için yazdım.
        for (int i = 0; i < personelTablosu.getRowCount(); i++) {
            // Her satırdaki ad ve soyad değerini aldım.
            String isim = personelTablosu.getValueAt(i, adColumnIndex).toString();
            String soyisim = personelTablosu.getValueAt(i, soyadColumnIndex).toString();
            // İsim ve soyisim birleştirilerek personelModel'e ekledim.
            personelModel.addElement(isim + " " + soyisim);
        }
        // isimListesine  personelModel verilerek personel isimleri eklenir.
        isimListesi.setModel(personelModel);


    }//GEN-LAST:event_dosyadanListeleActionPerformed

    private void soyad_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyad_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyad_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelListele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelListele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JButton dosyadanListele;
    private javax.swing.JButton dosyayaEkle;
    private javax.swing.JList<String> isimListesi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField maas_alani;
    private javax.swing.JTable personelTablosu;
    private javax.swing.JTextField soyad_alani;
    // End of variables declaration//GEN-END:variables
}
