/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kırtasiyeotomasyonuu;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Pars
 */
public class ürünSayfasi extends javax.swing.JFrame {

    Connection connection = null;
    DbHelper dbHelper = new DbHelper();
    PreparedStatement statement = null;
    ResultSet resultSet = null;

    public ürünSayfasi() {
        initComponents();
        setTitle("Ürün Ekle ");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Ana sayfanın kapatılmasını önlemek için

    }

    private void kategorigetir() throws SQLException {
        try {
            connection = dbHelper.getConnection();
            statement = connection.prepareStatement("SELECT * FROM kırtasiye.kategori");
            resultSet = statement.executeQuery();
            kategoriComboBox.removeAllItems();//veritabanındaki verileri tekrar tekrar göstermesin diye bunu kullandım
            // veritabanındaki kategori satırlarını dönen döngü oluşturdum.
            while (resultSet.next()) {
                //Her bir kategori adını kategoriComboBox'a eklemeli.
                kategoriComboBox.addItem(resultSet.getString("kategori"));
            }
        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }
    }

    private void markaGetir() throws SQLException {
        try {
            connection = dbHelper.getConnection();
            statement = connection.prepareStatement("SELECT * FROM kırtasiye.marka");
            resultSet = statement.executeQuery();
            markaComboBox.removeAllItems();//veritabanındaki verileri tekrar tekrar göstermesin diye bunu kullandım

            // veritabanındaki marka satırlarını dönen döngü oluşturdum.
            while (resultSet.next()) {
                //Her bir marka adını kategoriComboBox'a eklemeli.
                markaComboBox.addItem(resultSet.getString("marka"));
            }
        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        barkodNoAlani = new javax.swing.JTextField();
        kategoriComboBox = new javax.swing.JComboBox<>();
        markaComboBox = new javax.swing.JComboBox<>();
        urunAdiAlani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        stok_adedi = new javax.swing.JTextField();
        ekleButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barkod Numarası :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kategori :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marka : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ürün Adı :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fiyat :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stok Adedi :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ÜRÜN EKLE ");

        kategoriComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriComboBoxMouseClicked(evt);
            }
        });
        kategoriComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriComboBoxActionPerformed(evt);
            }
        });

        markaComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markaComboBoxMouseClicked(evt);
            }
        });
        markaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markaComboBoxActionPerformed(evt);
            }
        });

        ekleButonu.setText("EKLE");
        ekleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButonuActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(barkodNoAlani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(kategoriComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(markaComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(urunAdiAlani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(fiyat_alani, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(stok_adedi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ekleButonu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiyat_alani, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urunAdiAlani, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(markaComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kategoriComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stok_adedi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barkodNoAlani))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(ekleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(barkodNoAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(urunAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_adedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addComponent(ekleButonu)
                .addGap(17, 17, 17))
        );

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kategoriComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriComboBoxActionPerformed

    }//GEN-LAST:event_kategoriComboBoxActionPerformed

    private void markaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markaComboBoxActionPerformed

    }//GEN-LAST:event_markaComboBoxActionPerformed
    private void ekle() {

// Metin alanlarından girdileri almalı.
        String barkodNo = barkodNoAlani.getText();
        String urunAdi = urunAdiAlani.getText();
        String kategori = kategoriComboBox.getSelectedItem().toString();
        String marka = markaComboBox.getSelectedItem().toString();
        String stok_adedii = stok_adedi.getText();
        String fiyat = fiyat_alani.getText();

        try {
            // Stok adedi ve fiyatı tamsayıya dönüştürür.
            int stok = Integer.parseInt(stok_adedii);
            int fiyatt = Integer.parseInt(fiyat);

            connection = dbHelper.getConnection();

            // Ürünleri veritabanına eklemek için SQL sorgusunu hazırlamasını ve çalıştırmasını sağlar.            
            statement = connection.prepareStatement("INSERT INTO kırtasiye.ürünler(barkod_no, kategori, marka_adi, ürün_adi, fiyat, stok_adedi) VALUES (?, ?, ?, ?, ?, ?)");
            statement.setString(1, barkodNo);
            statement.setString(2, kategori);
            statement.setString(3, marka);
            statement.setString(4, urunAdi);
            statement.setInt(5, fiyatt);
            statement.setInt(6, stok);

            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ürün başarıyla eklendi.");

            barkodNoAlani.setText("");
            urunAdiAlani.setText("");
            fiyat_alani.setText("");
            stok_adedi.setText("");
            kategoriComboBox.removeAllItems();
            markaComboBox.removeAllItems();

        } catch (NumberFormatException ex) {
            // Eğer stok adedi veya fiyat tamsayıya dönüştürülemezse, kullanıcıya uygun bir hata mesajı gösterir.
            JOptionPane.showMessageDialog(this, "Miktar ve alış fiyatı tam sayı olmalıdır.");

        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }

    }

    private void ekleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButonuActionPerformed

        if (barkodNoAlani.getText().trim().isEmpty() || urunAdiAlani.getText().trim().isEmpty() || fiyat_alani.getText().trim().isEmpty() || stok_adedi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");
        } else {
            // Barkod numarası için doğrulama: 6 haneli bir rakam olmalı.
            Pattern pbarkod = Pattern.compile("[0-9]{6}+");
            Matcher mbarkod = pbarkod.matcher(barkodNoAlani.getText());

            // Ürün adı geçerli değilse, kullanıcıya uyarı vermeli
            Pattern purunAdi = Pattern.compile("^[a-zA-Z]+(\\s[a-zA-Z]+)?$");
            Matcher murunAdi = purunAdi.matcher(urunAdiAlani.getText());

            // Fiyat geçerli değilse, kullanıcıya uyarı vermeli
            Pattern pFiyat = Pattern.compile("\\d+");
            Matcher mFiyat = pFiyat.matcher(fiyat_alani.getText());

            // Stok adedi geçerli değilse, kullanıcıya uyarı vermeli
            Pattern pStok = Pattern.compile("\\d+");
            Matcher mStok = pStok.matcher(stok_adedi.getText());

            if (!mbarkod.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz barkod numarası girdiniz..");
            } else if (!murunAdi.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz ürün adı girdiniz . Türkçe karakter kullanmayınız....");
            } else if (!mFiyat.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz fiyat  girdiniz . ");
            } else if (!mStok.matches()) {
                JOptionPane.showMessageDialog(this, "Geçersiz stok adedi girdiniz.");
            } else {
                // Tüm kontroller başarılı ise, ekle metodunu çağırır.
                ekle();
            }
        }


    }//GEN-LAST:event_ekleButonuActionPerformed

    private void kategoriComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriComboBoxMouseClicked
        try {
            kategorigetir();
        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }
    }//GEN-LAST:event_kategoriComboBoxMouseClicked

    private void markaComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markaComboBoxMouseClicked
        try {
            markaGetir();
        } catch (SQLException ex) {
            dbHelper.ShowError(ex);
        }    }//GEN-LAST:event_markaComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ürünSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ürünSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ürünSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ürünSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ürünSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barkodNoAlani;
    private javax.swing.JButton ekleButonu;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> kategoriComboBox;
    private javax.swing.JComboBox<String> markaComboBox;
    private javax.swing.JTextField stok_adedi;
    private javax.swing.JTextField urunAdiAlani;
    // End of variables declaration//GEN-END:variables
}
